# Generated by Django 5.1.1 on 2024-10-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctionlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
