# Generated by Django 5.1.1 on 2024-10-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='list',
        ),
    ]
